-- MySQL Script generated by MySQL Workbench
-- ven. 11 sept. 2020 18:03:30 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Modifs faites : suppression de utf8 mb4-bin et
-- nom order en purchase
-- suppression plusieurs id dans purchase
DROP DATABASE ocpizza;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocpizza` ;
USE `ocpizza` ;

-- -----------------------------------------------------
-- Table `ocpizza`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(100) NOT NULL,
  `address2` VARCHAR(100) NULL,
  `zip_code` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ocpizza`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`restaurant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_restaurant_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_address_idx` ON `ocpizza`.`restaurant` (`address_id` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`restaurant` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_address_idx` ON `ocpizza`.`client` (`address_id` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `ocpizza`.`client` (`email` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`purchase_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`purchase_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`purchase_status` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`payment_method` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`payment_method` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`delivery_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`delivery_method` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`delivery_method` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`purchase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `total_price` DECIMAL(4,2) NULL,
  `client_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `purchase_status_id` INT UNSIGNED NOT NULL,
  `payment_method_id` INT UNSIGNED NOT NULL,
  `delivery_method_id` INT UNSIGNED NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`client_id`)
    REFERENCES `ocpizza`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`purchase_status_id`)
    REFERENCES `ocpizza`.`purchase_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`payment_method_id`)
    REFERENCES `ocpizza`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`delivery_method_id`)
    REFERENCES `ocpizza`.`delivery_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`pizza` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`ingredient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `portion` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`ingredient` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`recipe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT(500) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recipe_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_ingredient_idx` ON `ocpizza`.`recipe` (`ingredient_id` ASC);

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`recipe` (`pizza_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_purchase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pizza_unit` INT NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  `purchase_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pizza_purchase_pizza10`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_purchase_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `ocpizza`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_purchase` (`pizza_id` ASC);

CREATE INDEX `by_purchase_idx` ON `ocpizza`.`pizza_purchase` (`purchase_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `ocpizza`.`role` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`team` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_team_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ocpizza`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_role_idx` ON `ocpizza`.`team` (`role_id` ASC);

CREATE INDEX `by_restaurant_idx` ON `ocpizza`.`team` (`restaurant_id` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `ocpizza`.`team` (`email` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_ingredient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pizza_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pizza_purchase_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_ingredient` (`pizza_id` ASC);

CREATE INDEX `by_ingredient_idx` ON `ocpizza`.`pizza_ingredient` (`ingredient_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`stock` (
  `id` INT UNSIGNED NOT NULL,
  `available_stock` INT NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_restaurant_has_ingredient_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `stock_by_ingredient_idx` ON `ocpizza`.`stock` (`ingredient_id` ASC);

CREATE INDEX `stock_by_restaurant_idx` ON `ocpizza`.`stock` (`restaurant_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_restaurant` (
  `id` INT UNSIGNED NOT NULL,
  `available_amount` INT UNSIGNED NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pizza_has_restaurant_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_restaurant_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_restaurant_idx` ON `ocpizza`.`pizza_restaurant` (`restaurant_id` ASC);

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_restaurant` (`pizza_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
