-- MySQL Script generated by MySQL Workbench
-- ven. 11 sept. 2020 11:13:57 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- des PK supprimées, NOT NULL supprimées pour order
-- suppression COLLATE = utf8mb4_bin partout

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocpizza` ;
USE `ocpizza` ;

-- -----------------------------------------------------
-- Table `ocpizza`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adress1` VARCHAR(100) NOT NULL,
  `adsress2` VARCHAR(100) NULL,
  `zip_code` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_city_idx` ON `ocpizza`.`address` (`city` ASC);

CREATE INDEX `by_zip_code_idx` ON `ocpizza`.`address` (`zip_code` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`restaurant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  CONSTRAINT `fk_restaurant_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_address_idx` ON `ocpizza`.`restaurant` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_address_idx` ON `ocpizza`.`client` (`address_id` ASC);

CREATE INDEX `by_name_idx` ON `ocpizza`.`client` (`last_name` ASC);

CREATE INDEX `by_email_idx` ON `ocpizza`.`client` (`email` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`order_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_name_idx` ON `ocpizza`.`order_status` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`payment_method` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_name_idx` ON `ocpizza`.`payment_method` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`delivery_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`delivery_method` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_name_idx` ON `ocpizza`.`delivery_method` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME,
  `total_price` DECIMAL(4,2) NULL,
  `client_id` INT,
  `restaurant_id` INT,
  `order_status_id` INT UNSIGNED,
  `payment_method_id` INT UNSIGNED,
  `delivery_method_id` INT UNSIGNED,
  `address_id` INT UNSIGNED,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`client_id`)
    REFERENCES `ocpizza`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`order_status_id`)
    REFERENCES `ocpizza`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`payment_method_id`)
    REFERENCES `ocpizza`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`delivery_method_id`)
    REFERENCES `ocpizza`.`delivery_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`address_id`)
    REFERENCES `ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ocpizza`.`order` (`id` ASC);

CREATE INDEX `by_client_idx` ON `ocpizza`.`order` (`client_id` ASC);

CREATE INDEX `by_restaurant_idx` ON `ocpizza`.`order` (`restaurant_id` ASC);

CREATE INDEX `by_order_status_idx` ON `ocpizza`.`order` (`order_status_id` ASC);

CREATE INDEX `by_payment_method_idx` ON `ocpizza`.`order` (`payment_method_id` ASC);

CREATE INDEX `by_delivery_method_idx` ON `ocpizza`.`order` (`delivery_method_id` ASC);

CREATE INDEX `by_address_idx` ON `ocpizza`.`order` (`address_id` ASC);

CREATE INDEX `by_date_idx` ON `ocpizza`.`order` (`date` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_price_idx` ON `ocpizza`.`pizza` (`price` ASC);

CREATE INDEX `by_name_idx` ON `ocpizza`.`pizza` (`name` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`ingredient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `portion` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ocpizza`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`recipe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT(500) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `ingredient_id`, `pizza_id`),
  CONSTRAINT `fk_recipe_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_ingredient_idx` ON `ocpizza`.`recipe` (`ingredient_id` ASC);

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`recipe` (`pizza_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pizza_unit` INT NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `pizza_id`, `order_id`),
  CONSTRAINT `fk_pizza_order_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ocpizza`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_order` (`pizza_id` ASC);

CREATE INDEX `by_order_idx` ON `ocpizza`.`pizza_order` (`order_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ocpizza`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`team` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `role_id`, `restaurant_id`),
  CONSTRAINT `fk_team_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ocpizza`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_role_idx` ON `ocpizza`.`team` (`role_id` ASC);

CREATE INDEX `by_restaurant_idx` ON `ocpizza`.`team` (`restaurant_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_ingredient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pizza_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `pizza_id`, `ingredient_id`),
  CONSTRAINT `fk_pizza_order_pizza10`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_ingredient` (`pizza_id` ASC);

CREATE INDEX `by_ingredient_idx` ON `ocpizza`.`pizza_ingredient` (`ingredient_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`stock` (
  `id` INT UNSIGNED NOT NULL,
  `available_stock` INT NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `restaurant_id`, `ingredient_id`),
  CONSTRAINT `fk_restaurant_has_ingredient_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `stock_by_ingredient_idx` ON `ocpizza`.`stock` (`ingredient_id` ASC);

CREATE INDEX `stock_by_restaurant_idx` ON `ocpizza`.`stock` (`restaurant_id` ASC);


-- -----------------------------------------------------
-- Table `ocpizza`.`pizza_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocpizza`.`pizza_restaurant` (
  `id` INT UNSIGNED NOT NULL,
  `available_amount` INT UNSIGNED NOT NULL,
  `pizza_id` INT UNSIGNED NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `pizza_id`, `restaurant_id`),
  CONSTRAINT `fk_pizza_has_restaurant_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_restaurant_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `by_restaurant_idx` ON `ocpizza`.`pizza_restaurant` (`restaurant_id` ASC);

CREATE INDEX `by_pizza_idx` ON `ocpizza`.`pizza_restaurant` (`pizza_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
